version: "3"
services:
  app:
    container_name: go_starter
    restart: on-failure:10
    build: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=go_starter_postgres
      - MONGO_HOST=go_starter_mongo
    depends_on:
      - postgres
  postgres:
    container_name: go_starter_postgres
    image: postgres:13-alpine
    env_file:
      - .env
  mongo:
    container_name: go_starter_mongo
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: