version: "3"
services:
  app:
    container_name: go_starter
    build: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=go_starter_pg
    depends_on:
      - pg
    ports:
      - 8080:80
  pg:
    container_name: go_starter_pg
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - 5432:5432